import bpy


class LLMLidarSettings(bpy.types.PropertyGroup):
    base_config_path: bpy.props.StringProperty(
        name="Base Config",
        description="Path to the base scanner configuration JSON",
        subtype='FILE_PATH',
    )

    command_text: bpy.props.StringProperty(
        name="Command",
        description="Natural-language command for the LLM",
        default="",
    )

    llm_patch: bpy.props.StringProperty(
        name="Patch JSON",
        description="JSON patch generated by the LLM",
        default="",
    )

    scan_operator_id: bpy.props.StringProperty(
        name="Scan Operator",
        description="Operator idname used to trigger the scan",
        default="",
    )

    last_status: bpy.props.StringProperty(
        name="Status",
        description="Last status message",
        default="",
    )

    last_analysis_path: bpy.props.StringProperty(
        name="Last Analysis",
        description="Path to last analysis JSON",
        default="",
    )
